### ISSUE TITLE
How to stop curtains?

### ISSUE THREAD

**Issue by alejuu** [martinlaxenaire/curtainsjs#1]
Hi, 
First of all, I love curtainsjs. I'm working on a project and I want to stop the canvas animation when I click a button. But I can't find the way and I can't find anything related on the docs.

**Comment by martinlaxenaire** [comment]
Hi alejuu,

sorry I hadn't seen your message.

There are mutliple ways to do it depending on how you handle your animations.
If you are using uniforms to animate the curtains, you might want to set a flag (boolean) in your javascript that controls whether you update your uniforms or not.
Or you can also pass that flag as a uniform to your shader and handle it there.
