### ISSUE TITLE
Incorrect sampler name

### ISSUE THREAD

**Issue by englishtom** [martinlaxenaire/curtainsjs#105]
**Describe the bug**
I am attempting to load a new video source using Plane.loadSource. This works correctly, however, if I have previously created a texture using Plane.createTexture then the newly created texture from Plane.loadSource has the sampler name from Plane.createTexture, rather than the sampler name that was passed in Plane.loadSource.

**To Reproduce**

1. Create a new texture with a sampler name using Plane.createTexture

`plane.createTexture({ sampler: "activeTexture" });`

2. Load a new source using Plane.loadSource and pass a sampler name:

 `plane.loader.loadVideo(src, { sampler: 'myNamedTexture' } );`

3. The sampler name of the texture created in step 2 will have the sampler name passed in step 1.

JSFiddle reproduction of issue here - https://jsfiddle.net/englishtom86/z7tx69ur/67/

**Expected behavior**
Both textures will have the given sampler names

**Comment by martinlaxenaire** [comment]
Hey @englishtom, there was indeed a bug with the texture options when using `createTexture`. This should be fixed with the latest version.

Cheers,

**Comment by englishtom** [comment]
Super! Looks fixed to me.
