### ISSUE TITLE
blocked because of a disallowed MIME type

### ISSUE THREAD

**Issue by winniejo** [martinlaxenaire/curtainsjs#106]
Hay 
I am using xampp from my desktop and downloaded the Git files. 
I get this message while it's pointing to the correct map the "index.mjs" was blocked. Did not have this problem for a long time with other projects and files , any advice ?

error message (using Xampp):
"http://localhost/1/src/index.mjs” was blocked because of a disallowed MIME type (“”) "

**Comment by martinlaxenaire** [comment]
Hi @winniejo,

I can't say with so few informations.
Are you using a bundler? If not, are you using the `type="module"` attribute on your main script tag? Have you tried with the umd version?

Cheers,

**Comment by winniejo** [comment]
Iam not using a bundler. 
I just downloaded the code + example files from Github and dumped it ("as is") in the  xampp root htdocs / curtainsjs-master / examples / simple-plane / index.html and run it.   If it were the "simple-plane" index or any other example it throws the same error in my console:
I used it on FF, Chrome and Safari 
======
Errors:
"Loading module from “http://localhost/1/src/index.mjs” was blocked because of a disallowed MIME type (“”)".    -  index.html

Watnings:
"Loading failed for the module with source “http://localhost/1/src/index.mjs”. -     index.html:56:1

"Some cookies are misusing the recommended “SameSite“ attribute 3 "
=========

I also did not touch the code in the index.html or any other files, so it should run! Or am I missing something?

**Comment by martinlaxenaire** [comment]
This might have to do with Xamp not recognizing `*.mjs` files as javascript. Maybe this can help? https://stackoverflow.com/a/59595485/13354068

**Comment by winniejo** [comment]
So its fixed for me by renaming "index.jsm" to "index.js"
that is strange...  it simply cant recognize .jsm.

Although Iam using this now on an older mac, software and browsers, .jsm  from other libs are been recognized.

well have a nice one, cheers.
