### ISSUE TITLE
Copying a texture with different sourceType doesn't work

### ISSUE THREAD

**Issue by GeorgeHastings** [martinlaxenaire/curtainsjs#107]
I'm trying to copy a texture from a RenderTarget into an already existing canvas texture. I can see the expected result in the FBO in Spector, but it doesn't render the new texture in the final output. 

Effectively I'm trying to replace one texture with another, regardless of their sourceType (fbo => canvas, or canvas => fbo). The codepen below reproduces the behavior:

https://codepen.io/georgehastings/pen/OJwJoKd?editors=0110

**Comment by martinlaxenaire** [comment]
I @GeorgeHastings,

to copy a RenderTarget texture, you should instead create a new Texture.
Here's a working codepen: https://codepen.io/martinlaxenaire/pen/ExpaEKR?editors=0110

Hope that helps.

Cheers,

**Comment by GeorgeHastings** [comment]
Let's say I have an arbitrary texture called "uTexture". I want to dynamically copy in either a separate fbo or canvas texture into uTexture. This could go back and forth any number of times, all the while preserving uTexture on screen. 

Is this possible?

**Comment by martinlaxenaire** [comment]
Hi @GeorgeHastings,

FBO textures are handled differently than other textures in WebGL, that's why it doesn't work.
I guess you should use 2 separate textures (one for the FBO, one for the canvas) and use a separate uniform in your shader to switch between those two.

Cheers,

**Comment by GeorgeHastings** [comment]
Yeah that makes sense, noticed different properties in the object. I had started exploring that direction, will give it another look. Thanks!
