### ISSUE TITLE
Planes have unwanted offset when page is refreshed after scroll on mobile

### ISSUE THREAD

**Issue by GeorgeHastings** [martinlaxenaire/curtainsjs#117]
When I refresh my browser on mobile (Safari iOS and iPhone emulator in Chrome devtools), after having scrolled down the page, my static scenes inherit unwanted scrollDeltaY (the scene is way offset to the top or totally not visible). 

I have curtains object and plane `watchScroll` set to `false`. My scenes are rendered inside divs in the DOM flow (not fixed full width). 

I tried using the provided methods like `updateScrollValues` / `updateScrollPosition` to no effect. 

I have a hacky fix for it, before creating my Planes, I add this line:
```
if (isMobile()) {
   window.scroll(0, 0);
}
```
The window jumps to the top and then back to the initial scroll position, usually fixing it but it's not perfect.

Any help would be appreciated!

**Comment by martinlaxenaire** [comment]
Hey @GeorgeHastings,

Your issue reminds me of https://github.com/martinlaxenaire/curtainsjs/issues/18 even tho it's hard to say without a minimal reproduction example.

You could try to patch/remove this portion of code and see it fixes the bug: https://github.com/martinlaxenaire/curtainsjs/blob/master/src/core/Renderer.js#L412

Let me know if that helps.

Cheers,
