### ISSUE TITLE
Typescript declaration file missing

### ISSUE THREAD

**Issue by joebentaylor** [martinlaxenaire/curtainsjs#12]
I can no longer render anything as no declaration file can be fouund, i get this error when i use the es6 import method:

`module "/Users/joetaylor/Documents/www/airpay-2019-website/node_modules/curtainsjs/libs/curtains.min"
Could not find a declaration file for module 'curtainsjs'. '/Users/joetaylor/Documents/www/airpay-2019-website/node_modules/curtainsjs/libs/curtains.min.js' implicitly has an 'any' type.
  Try `npm install @types/curtainsjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'curtainsjs';`ts(7016)
Could not find a declaration file for module 'curtainsjs'. '/Users/joetaylor/Documents/www/airpay-2019-website/node_modules/curtainsjs/libs/curtains.min.js' implicitly has an 'any' type.
  Try `npm install @types/curtainsjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'curtainsjs';`ts(7016)`

**Comment by joebentaylor** [comment]
After a lot of research, it seem a few libraries like Tweenmax etc have the same issue, but this doesnt halt the dependencies being used.

In one of my other projects Curtains works fine, but when i try to use it in a new project with the exact same code. it no longer works

**Comment by martinlaxenaire** [comment]
Hi @joebentaylor,

Did you have a look at that SO thread: https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam ?

**Comment by joebentaylor** [comment]
I did, but this doesnt fix my issue

this is my codesandbox.

Maybe you could shine a light for me?



(By the way, this code works fine on my own project)

https://codesandbox.io/s/w792nljpqk

**Comment by martinlaxenaire** [comment]
Your codesandbox example is successfully compiling and there are no js error neither.
I can't help you on that one as I'm not using Typescript really.
Looks more like a Gatsby/Typescript issue anyway.

**Comment by joebentaylor** [comment]
Hmmm, its really strange, as my other gatsby project compiles the exact same and works fine... very bizzare

**Comment by joebentaylor** [comment]
Id just like to post my fix as i think this will help a lot of people!!!

In my sandbox at the time i had
`<canvas id="canvas" />`

but it should have been:
`<div id="canvas" />`


that was it! All sorted now :)
