### ISSUE TITLE
API to access camera position

### ISSUE THREAD

**Issue by ajayns** [martinlaxenaire/curtainsjs#17]
The curtains class allows you to specify or access `fov` using `params` I believe. I'd like to access the Camera position the same way.

The problem I'm facing is while attempting to design an image grid to fullscreen animation using WebGL and shaders. So I'd like to calculate the dimensions of the viewport using camera fov and position.z.

**Comment by martinlaxenaire** [comment]
Hi @ajayns,

all the internal maths are done assuming the camera Z position is always equal to `(fov / 2)`. You should be able to use that number in your calculations.

**Comment by ajayns** [comment]
Thank you that works for me! Maybe it'd help to add that in the docs somewhere?
I'm closing this issu.

**Comment by martinlaxenaire** [comment]
Thanks @ajayns for the feedback!
Even tho there's no real camera object in the lib, I'll add that in the docs, couldn't hurt.
