### ISSUE TITLE
Plane inside plane or make ShaderPass work like a plane?

### ISSUE THREAD

**Issue by mylesnguyen** [martinlaxenaire/curtainsjs#19]
The animation I'm trying to make requires 3d position work that affects all the planes inside as a whole. Shader passes would've served this purpose but as I read it does not have projection and model view matrices.
Getting everything inside a bigger plane is also not possible yet?

What's the workaround? Awesome library btw.

**Comment by martinlaxenaire** [comment]
Hi @mylesnguyen,

based on what I understand of the effect you're trying to achieve, I see 2 possible solutions:
- use a shader pass and fake a 3D effect in the fragment shader, kind of like the fake "fish eye effect" of this example: https://www.curtainsjs.com/examples/post-processing-scroll-effect/index.html
- add an effectValue uniform to all your planes, update its value based on whatever will trigger your effect (you could use the planes positions using plane.getWebGLBoundingRect() for example) and use it in your vertex shader calculations.

Anyway I'm closing this as it is not really an issue.

**Comment by mylesnguyen** [comment]
I did think of the 1st solution as well but sounds kind of beyond my level.
The 2nd one is actually not bad. Though still a bit complicated, I'm going to give it a shot.

Hopefully there'll be a much simple method in the future. Thanks for your suggestion.
