### ISSUE TITLE
Show a trail in glsl

### ISSUE THREAD

**Issue by AlainBarrios** [martinlaxenaire/curtainsjs#24]
I want to make a trace with the mouse but the circle is not drawn, could you help me with this, I already made the passes but nothing appears

This is what I have so far
https://codepen.io/AlainBarrios/pen/WNvoaXx

**Comment by martinlaxenaire** [comment]
Hi @AlainBarrios,

I don't know what you're trying to do with your shaders, didn't take the time to analyze them, but my guess is that's what's not working here. Have you tried with the exact example uniforms names and shaders?

Not a library issue anyway so I'll be closing this soon. I'm considering creating an official slack channel for those kind of needs but I'm afraid I'd feel lonely in there 🤣

**Comment by AlainBarrios** [comment]
I am trying to create this trail with the mouse

https://codropspz-tympanus.netdna-ssl.com/codrops/wp-content/uploads/2019/12/Akaru.mp4
