### ISSUE TITLE
Image position

### ISSUE THREAD

**Issue by alexey13** [martinlaxenaire/curtainsjs#25]
Good day! Thank you for the awesome plugin. Can you please tell me is there a way to render the image with 'padding'. The issue is that when shader applied the image gets cut off from sides. It looks like an image trying to fill a plane fully, like cover in CSS. But I need like contain.
Tried: drawCheckMargins but nothing changed, played with image size by CSS in plane but its not working too.
Thanks in advance

**Comment by martinlaxenaire** [comment]
Hi @alexey13,

at the moment the library indeed only provides a solution for the images to behave like cover in CSS.
One solution might be to let the image define the size of your plane and then resize the plane once the image has loaded, as shown in this codepen: https://codepen.io/martinlaxenaire/pen/GRJOxrO
However this works if your plane contains only one image.

To get something similar as CSS contain with multiple images, one idea might be to modify the texture coordinates in your shader based on the textures matrices values and discard the unappropriate pixels left on the edges.

Hope this helps!

**Comment by alexey13** [comment]
Thank you, will try those methods!
