### ISSUE TITLE
displacement image aspect ratio

### ISSUE THREAD

**Issue by stefanocurnis** [martinlaxenaire/curtainsjs#26]
Hey guys.
Fantastic library!

https://www.curtainsjs.com/examples/multiple-textures/index.html

I was playing around with this demo but I can't figure out how to make the displacement image to respect its aspect ratio while covering the whole texture (sort of like "backgound-size:cover or object-fill:cover;)

I put a black text inside the displacement image in order to have a cool effect, but when I resize the screen, the text stretches... any ideas?

Thank you for your help!

**Comment by martinlaxenaire** [comment]
Hi @stefanocurnis,

You can easily achieve the cover effect using your displacement texture matrix uniform. Pass the modified texture coords as a varying to your fragment shader and use them to map your displacement texture.

`vDisplacementCoord = (displacementMatrix * vec4(aTextureCoord, 0.0, 1.0)).xy;`

However it might crop the text in portrait mode on devices like mobile phones.
When it comes to display text elements as textures, I usually tend to write them in a canvas and use that canvas as a separate texture. That way you can control the text size on resize, change the text content directly in the HTML, etc.

Here are some examples that use that trick:
https://github.com/martinlaxenaire/curtainsjs/blob/master/examples/multiple-planes-canvas-text/js/multiple.planes.canvas.setup.js
https://codepen.io/AlainBarrios/pen/jOOKWNX

There are also other ways to display text in WebGL explained in this article: https://css-tricks.com/techniques-for-rendering-text-with-webgl/ but I did not find the time to try it myself yet.

Cheers,
