### ISSUE TITLE
Curtain.js + Squarespace?

### ISSUE THREAD

**Issue by dearnaomichan** [martinlaxenaire/curtainsjs#27]
Hello!
I am following your [tutorial on CSS Tricks](https://css-tricks.com/animate-images-and-videos-with-curtains-js/), I am trying to get your first example in the tutorial working on Squarespace. Not sure if you are familiar with Squarespace. But I am using a Code Block for the HTML and injecting the JS into the header of the page. It's turning out to be black, would you have an insight on why that is?

The warnings I am getting make me think it's limits Squarespace has put on the template, but I wondered if you have seen them before? It looks like curtain.js is loading fine but the image is being blocked.

Specifically this warning... 
`Access to image at 'https://static1.squarespace.com/static/5dc0741018cb921d7dead1d7/t/5e6d6368e095af7f34d6a373/1584227183147/DSC06867-c-barbari-cbd-shop-cbd-flower-joints-cbd-prerolls-herbal-cigarettes-hemp.png' from origin 'https://www.naomichan.info' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*,*', but only one is allowed.`

[This is where I'm testing this](https://www.naomichan.info/testing-curtain-js), please take a look and if you have any insight, would be extremely helpful!

**Comment by martinlaxenaire** [comment]
Hi @dearnaomichan,

this is a CORS issue related to squarespace and not the library itself: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

You can try to host the image on a different server or use a image from unsplash for example.

Cheers,
