### ISSUE TITLE
Bug: Setting plane.alwaysDraw = true never draws the plane

### ISSUE THREAD

**Issue by ajayns** [martinlaxenaire/curtainsjs#29]
Code to reproduce: 
```javascript
const plane = this.curtains.addPlane(el, params);

if (plane) {
  plane.alwaysDraw = true;
}
```

I've also tried putting this line in the plane.onReady function, but the issue still persists.

**Comment by martinlaxenaire** [comment]
Hi @ajayns ,

`alwaysDraw` should be passed as an initial parameter when adding your plane, not after its creation:

`params.alwaysDraw = true;
const plane = this.curtains.addPlane(el, params);`

This should work.
Let me know if it fixed your bug!

Cheers,

**Comment by ajayns** [comment]
Oh that fixed it. Do all plane parameters work like this?
