### ISSUE TITLE
Use more than two images

### ISSUE THREAD

**Issue by dr-okra** [martinlaxenaire/curtainsjs#3]
Is there a way to use more than two images?  I'd love to make a slideshow using different images and displacement maps if possible, but I don't know if it's possible to do this.

**Comment by martinlaxenaire** [comment]
Hi @dr-okra,

You could use as many images as you want. You may want to use one or two uniform to keep tracks of the visible slides (like activeSlide and nextSlide) and then mix the textures inside your fragment shader.

**Comment by AlexisMathewHindle** [comment]
Hi Martin,
Love what you've done with curtains.js! 
Just trying to create, like dr-okra a slideshow using more than two images but struggling... Add other images to html with relevant data-sampler attribute. Then added texture samplers but unfortunately only keep getting two images. Code it below. Any help would be massively appreciated! 


`
	<body>
        <div id="page-wrap">

			<div id="canvas"></div>

			<div class="flex-wrapper multi-textures" data-vs-id="multiple-textures-vs" data-fs-id="multiple-textures-fs">
				<span>Click me !</span>
				
				<img src="images/displacement.jpg" data-sampler="displacement" />
				<img src="images/plane-texture-1.jpg" data-sampler="firstTexture" />
				<img src="images/plane-texture-2.jpg" data-sampler="secondTexture" />
				<img src="images/plane-texture-3.jpg" data-sampler="thirdTexture" />
			</div>
		</div>

        <script id="multiple-textures-vs" type="x-shader/x-vertex">
			#ifdef GL_ES
			precision mediump float;
			#endif

			// default mandatory variables
			attribute vec3 aVertexPosition;
			attribute vec2 aTextureCoord;

			uniform mat4 uMVMatrix;
    		uniform mat4 uPMatrix;

			// custom variables
			varying vec3 vVertexPosition;
			varying vec2 vTextureCoord;

			// custom uniforms
			uniform float uTransitionTimer;
			uniform vec2 uResolution;


			void main() {

				vec3 vertexPosition = aVertexPosition;

			   	gl_Position = uPMatrix * uMVMatrix * vec4(vertexPosition, 1.0);

			   	// varyings
			   	vTextureCoord = aTextureCoord;
			   	vVertexPosition = vertexPosition;
			}
        </script>
        <script id="multiple-textures-fs" type="x-shader/x-fragment">
			#ifdef GL_ES
			precision mediump float;
			#endif

			varying vec3 vVertexPosition;
			varying vec2 vTextureCoord;

			// custom uniforms
			uniform float uTransitionTimer;
			uniform vec2 uResolution;

			// our textures samplers
			// notice how it matches our data-sampler attributes
			uniform sampler2D firstTexture;
			uniform sampler2D secondTexture;
			uniform sampler2D thirdTexture;
			uniform sampler2D displacement;

			void main( void ) {
				// our texture coords
				vec2 textureCoords = vec2(vTextureCoord.x, vTextureCoord.y);

				// our displacement texture
				vec4 displacementTexture = texture2D(displacement, textureCoords);

				// slides transitions based on displacement and transition timer
				vec2 firstDisplacementCoords = textureCoords + displacementTexture.r * ((cos(uTransitionTimer / (120.0 / 3.141592)) + 1.0) / 2.0);
				vec4 firstDistortedColor = texture2D(firstTexture, firstDisplacementCoords);

				// same as above but we substract the effect
				vec2 secondDisplacementCoords = textureCoords - displacementTexture.r * ((cos((uTransitionTimer + 120.0) / (120.0 / 3.141592)) + 1.0) / 2.0);
				vec4 secondDistortedColor = texture2D(secondTexture, secondDisplacementCoords);

				// slides transitions based on displacement and transition timer
				// vec2 thirdDisplacementCoords = textureCoords + displacementTexture.r * ((cos(uTransitionTimer / (120.0 / 3.141592)) + 1.0) / 2.0);
				// vec4 thirdDistortedColor = texture2D(thirdTexture, thirdDisplacementCoords);

				// mix both texture
				vec4 finalColor = mix(firstDistortedColor, secondDistortedColor,  ((cos(uTransitionTimer / (120.0 / 3.141592)) + 1.0) / 2.0));

				// handling premultiplied alpha
				finalColor = vec4(finalColor.rgb * finalColor.a, finalColor.a);

				gl_FragColor = finalColor;
			}
        </script>


		<script src="../../build/curtains.js" type="text/javascript"></script>
        <script src="js/multiple.textures.setup.js" type="text/javascript"></script>

`

**Comment by martinlaxenaire** [comment]
Hi @AlexisMathewHindle,

here's a link to a codepen that is working : https://codepen.io/martinlaxenaire/full/KeQpLO/
I've commented the code so you should be able to understand how it works.

Let me know if it's ok!

**Comment by AlexisMathewHindle** [comment]
Hi @martinlaxenaire 

You are an absolute legend!Thank you very much! That was a huge help.
Unfortunately I haven't got it working yet...

I forgot to mention that I'm using curtains.js in an app that I'm building Angular 6. When I come to to serve it locally I'm getting an error

` error TS2304: Cannot find name 'Curtains'.`

Even though this is error is occurring I am getting this

<img width="1228" alt="screen shot 2018-06-19 at 22 28 17" src="https://user-images.githubusercontent.com/25738271/41625265-1d4da23e-7410-11e8-91bc-7dd3196f926a.png">

Which is promising but not quite there... At moment when I place the vertex and shaders in the index.html I get 

<img width="1219" alt="screen shot 2018-06-19 at 22 30 03" src="https://user-images.githubusercontent.com/25738271/41625324-5c31840c-7410-11e8-819a-732653167504.png">

`Unable to find the vertex or fragment shader`

I'm not sure why this is as they are very much there as I can see them. Instead when I place them in the app.component I get the black screen like in the image above.

Any thoughts would be massively appreciated.

Thanks you very much!

**Comment by martinlaxenaire** [comment]
Hi @AlexisMathewHindle,

the most important thing here is: 

```
Errors occurred while compiling the shader:
ERROR: 0:3: 'medium' : syntax error
```

Which means your shader is not compiling.
My guess here is that you made a typo and wrote "medium" instead of "mediump". Try with:

```
#ifdef GL_ES
	precision mediump float;
#endif
```

However I may add a patch to avoid throwing a js error when the shaders aren't compiling.

**Comment by AlexisMathewHindle** [comment]
Hi @martinlaxenaire,

Thank you so much for this! Great help! The typo was indeed causing an error but sadly it isn't the main issue. I'm still getting 

`error TS2304: Cannot find name 'Curtains'.`

So therefore only getting the default vertex and fragment shaders which is why I'm getting a black background, right?
Is there a way of passing the shaders in the params so that I don't need to have them within script tags in html?

Thank you so much for your help!

**Comment by martinlaxenaire** [comment]
Hey @AlexisMathewHindle,

looks like an Angular config problem to me, see https://github.com/angular/angular/issues/4902

I was thinking of adding a way to pass shaders via strings anyway so I just pushed an update. You can now pass strings to "vertexShader" and "fragmentShader" params (check the updated documentation).

**Comment by AlexisMathewHindle** [comment]
Hi @martinlaxenaire,

Amazing! That worked! Thank you very much!
One last question - I promise!
If I wanted to change the way the direction the displacement images 'fades' in do I have have to amend the effectFactor. I'm trying to get the image to 'fade in' from the right on click.

You've been a HUGE help! Thank you so much!

**Comment by martinlaxenaire** [comment]
Yep, you'd have to tweak the effectFactor a bit. Remember that the texture coordinates are ranging from 0 (left side) to 1 (right side) on the X axis.

You could try with:

`vec2 effectFactor = vec2(textureCoords.x * 0.75, (textureCoords.y - 0.5) * 0.75);`

Or even with a constant:

`vec2 effectFactor = vec2(2.0, (textureCoords.y - 0.5) * 0.75);`

Just play with it (or have a look at how are working other displacement shaders elsewhere)

**Comment by AlexisMathewHindle** [comment]
Good morning @martinlaxenaire,

Thank you very much for this. Was a massive help. Had a good play and managed to get the effect I was looking for.

Out of curiosity I'm looking to wrap several 'layered' images in a div in order to create a parallax motion effect on mousemove. Do you think this might be possible?

So far I've managed to get it working for one parallax container but can't seem to get it working when I add another one... 

`<div class="page-wrap">
  <div id="canvas"></div>

  <div class="flex-wrapper multi-textures" data-vs-id="multiple-textures-vs" data-fs-id="multiple-textures-fs">
    <div class="change-slide__container">
      
      
    </div>


    
    
    <div class="cd-background-wrapper" data-sampler="firstTexture" >
      <figure class="cd-floating-background">
        <img class="layer-one" src="assets/img/cd-img-1.jpg"/>
        <img class="layer-two" src="assets/img/cd-img-2.png"/>
        <img class="layer-three"src="assets/img/cd-img-3.png"/>
      </figure>
    </div>

      
    <div class="cd-background-wrapper" data-sampler="secondTexture" >
      <figure class="cd-floating-background">
        <img class="layer-one" src="assets/img/jlr-foreground.png"/>
        <img class="layer-two" src="assets/img/jlr-car.png"/>
        <img class="layer-three"src="assets/img/jlr-background.png"/>
      </figure>
    </div>

    
    <img src="assets/img/displacement/6.jpg" data-sampler="displacement" />

    
    <img src="assets/img/main-test.png" data-sampler="firstTexture" />
    <img src="assets/img/Img23.jpg" data-sampler="secondTexture" />
    <img src="assets/img/Img25.jpg" data-sampler="thirdTexture" />
    <img src="assets/img/Img24.jpg" data-sampler="fourthTexture" />
  </div>

</div>

<app-timeline></app-timeline>`

Do I need to load each container and push to an array and load like you've done for video and images?

Any advice would be massively appreciated.

Hope you have an awesome day!

**Comment by martinlaxenaire** [comment]
Hi @AlexisMathewHindle,

I'm not sure I understand what you want to achieve (and we're going a little bit off topic here.). You could post a jsfiddle/codepen so I can look. Also, data-sampler attributes should be used on img tags.

With something like this you can have a basic parallax layer effect if that's what you're trying to do:

```
<div class="curtain">
	<img src="images/background.jpg" data-sampler="backgroundTexture" />
	<img src="images/front.png" data-sampler="frontTexture" />
</div>
```

```
#ifdef GL_ES
    precision mediump float;
#endif

uniform vec2 uMousePosition;

varying vec3 vVertexPosition;
varying vec2 vTextureCoord;

uniform sampler2D backgroundTexture;
uniform sampler2D frontTexture;

void main( void ) {

    // get our texture coords
    vec2 textureCoords = vec2(vTextureCoord.x, vTextureCoord.y);

    vec2 mouseToTextCoords = vec2((uMousePosition + 1.0) / 8.0);

    // background layer
    vec4 backgroundText = texture2D(backgroundTexture, textureCoords + (uMousePosition / 50.0));
    // front layer (with transparency)
    vec4 frontText = texture2D(frontTexture, textureCoords + (uMousePosition / 30.0));

    // mix both texture based on front texture transparency
    vec4 finalColor = mix(backgroundText, frontText, frontText.a);

    // handling premultiplied alpha (useful if we were using a png with transparency)
    finalColor = vec4(finalColor.rgb * finalColor.a, finalColor.a);

    gl_FragColor = finalColor;
}
```

**Comment by dr-okra** [comment]
I just want to thank you for your efforts Martin. Much respect

**Comment by rogierhofboer** [comment]
Unfortunatelty this stopped working with the latest version of curtains js.
The addPlane() method is not available anymore, and when changing to new Plane() nothing is displayed.
Could someone provide an updated example on how to do this. Preferable with both pictures and videos in the same slideshow? (Now .images is hard-coded) Many thanks in advance!
