### ISSUE TITLE
Using a canvas as a plane element

### ISSUE THREAD

**Issue by mogmog** [martinlaxenaire/curtainsjs#33]
As I understand it, curtainsjs is built to render either an image or a video.

Is it possible to, instead, use a canvas element? Possibly one that is animating? 

I tried just adding a canvas in the html but that didnt work, see here.

https://codepen.io/mogmog-the-scripter/pen/JjYKWGV

**Comment by AlainBarrios** [comment]
> As I understand it, curtainsjs is built to render either an image or a video.
> 
> Is it possible to, instead, use a canvas element? Possibly one that is animating?
> 
> I tried just adding a canvas in the html but that didnt work, see here.
>
> https://codepen.io/mogmog-the-scripter/pen/JjYKWGV

It is possible, just convert the canvas to a texture and update it
**here a example** https://codepen.io/AlainBarrios/pen/jOOKWNX

**Comment by martinlaxenaire** [comment]
Hi @mogmog,

As @AlainBarrios said, it is possible to use a canvas element as a texture. There's even an example here:
https://www.curtainsjs.com/examples/simple-canvas-plane/index.html

In fact, your codepen example is working, it's just that you are not using your canvas texture (with "uSampler1" as sampler uniform name) inside your fragment shader.
Also, you might want to hide your original canvas with `display: none;` in your CSS.

Cheers,
