### ISSUE TITLE
Video url not working with curtains

### ISSUE THREAD

**Issue by tanyacruz** [martinlaxenaire/curtainsjs#34]
Hi, I'm trying to to create a video displacement shader using the example available here: https://css-tricks.com/animate-images-and-videos-with-curtains-js/

I want to create the exact same effect. This is working fine when my video sources are in the directory, or if I use the links available in your example. However when I change the video source to a url the videos do not play. I have double checked that the urls are correct, and they work fine when in a video html tag, just not when I am using curtains. I'm trying to figure out the problem because a url can clearly work as it works when I use the links in the example. Let me know if you have any suggestions! Thanks.

**Comment by AlainBarrios** [comment]
> Hola, estoy tratando de crear un sombreador de desplazamiento de video usando el ejemplo disponible aquí: https://css-tricks.com/animate-images-and-videos-with-curtains-js/
> 
> Quiero crear exactamente el mismo efecto. Esto funciona bien cuando mis fuentes de video están en el directorio, o si uso los enlaces disponibles en su ejemplo. Sin embargo, cuando cambio la fuente de video a una URL, los videos no se reproducen. He comprobado que las URL son correctas y funcionan bien en una etiqueta de video html, pero no cuando estoy usando cortinas. Estoy tratando de resolver el problema porque una URL puede funcionar claramente cuando uso los enlaces en el ejemplo. ¡Avísame si tienes alguna sugerencia! Gracias.


You can only use html elements

**Comment by martinlaxenaire** [comment]
Hi @tanyacruz,

This is a CORS related issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

You should try to host your videos yourself or use videos hosted on servers that allows CORS.

Cheers,

**Comment by tanyacruz** [comment]
great that makes sense! thanks for the clarification and links :)
