### ISSUE TITLE
Locomotive scroll example doesn't work on WebKit browsers

### ISSUE THREAD

**Issue by Serse** [martinlaxenaire/curtainsjs#36]
Hello,

It looks like that [Locomotive scroll example](https://www.curtainsjs.com/examples/multiple-planes-scroll-effect-custom-scroll/index.html) doesn't work correctly on Mac WebKit desktop browsers (Chrome and Safari).

Even fixing the console error 
`curtains.js:5319 Uncaught ReferenceError: module is not defined
    at curtains.js:5319`
by using the minified js, the planes are not showed on WebKit browsers.

![image](https://user-images.githubusercontent.com/1125973/80378148-853f1100-889c-11ea-9f04-b32a4874e070.png)

Can you check?

Great library, thank you.
Marco

**Comment by martinlaxenaire** [comment]
Hi @Serse,

There was indeed a bug where the `onReady` plane callback was not always firing. That should be fixed with v6.0.3 now.
Thanks for the bug report!

Cheers,

**Comment by Serse** [comment]
Updating the OS has fixed the issue, Thanks
