### ISSUE TITLE
Curtains glitches when using a JS Router

### ISSUE THREAD

**Issue by ajayns** [martinlaxenaire/curtainsjs#38]
I've set up a basic code sandbox to illustrate the issue: https://codesandbox.io/s/fervent-dust-43spf

I'm using a very simple router setup which adds page content and removes the previous page content. So for curtains, I'm removing planes and adding new ones on route change. But this seems to be causing a couple of glitches once the transition is done - the images aren't loaded in position/right manner.

Additional note: Async textures or so isn't the solution I'm looking for cause the planes in different pages will have different positions/layouts, this example is just to illustrate the bug in the simplest manner

**Comment by martinlaxenaire** [comment]
Hey @ajayns, 

I've had a quick look at this and I think the issue is coming from the way you're using Highway.js router rather than the lib. Actually this is not even a bug, I think it's more like you're adding the planes at a point when the router transition is not totally finished yet.

If you replace this part:

```javascript
onEnter() {
    wgl.init("home");
}
```

By that, this should work:

```javascript
onEnterCompleted() {
    wgl.init("home");
}
```

Let me know if that works for you!

Cheers,

**Comment by ajayns** [comment]
Ahh, I figured it might be that but kept it as onEnter itself in case I wanted any animations using Curtains during the transition. I'll just figure a way around that to give that effect without initializing the plane mid-transition I guess.

Thanks a bunch for your quick response as always @martinlaxenaire 
Appreciate it!

Another quick question if you don't mind me asking, would you recommend any strategy for preloading images into Curtains or do I just use my usual JS preloader?

**Comment by ajayns** [comment]
Closing the issue since resolved.

**Comment by martinlaxenaire** [comment]
I think you might be able to do it in the `onEnter` callback, maybe by setting an absolute position to the parent elements or something like that. Looks more like a CSS positioning thing to me.

As for images loading, you can use your usual JS preloader for now.
But it could be great indeed to write a preloader that would allow an early GPU upload of the assets. I'll have a look at that someday when I have time.

Cheers,

**Comment by ajayns** [comment]
Thanks for your time Martin!
