### ISSUE TITLE
[Performance] Hide elements not in view

### ISSUE THREAD

**Issue by 23d1** [martinlaxenaire/curtainsjs#39]
Not sure if this is something already implemented (sorry, I should sift through the code), but it would be beneficial for pages with tons of content, or pages with infinite (lazy loaded or otherwise) content and so forth, to hide elements that are not in view. Would there be any benefit to adding that to the library, or perhaps a plugin API with subsequent plugins for curtains.

**Comment by 23d1** [comment]
Oh my. I just realized you've made some major updates since v. 4+... 💯  I need to `yarn upgrade` more across projects.

**Comment by martinlaxenaire** [comment]
Hey @23d1,

glad to hear that! I'm closing the issue then.
