### ISSUE TITLE
Missing NPM package

### ISSUE THREAD

**Issue by UstymUkhman** [martinlaxenaire/curtainsjs#4]
Hi, I've recently tried curtainsjs and really liked it, nice project!
Although I can't find an NPM module of this library to install with node or yarn.
Could you create one, please? It would be very useful, thanks a lot! 😄

**Comment by martinlaxenaire** [comment]
Hi @UstymUkhman,

I've created a npm package of the lib that you can now find here : https://www.npmjs.com/package/curtainsjs

Thanks,
