### ISSUE TITLE
 Problems with adding textures

### ISSUE THREAD

**Issue by AlainBarrios** [martinlaxenaire/curtainsjs#40]
I have problems with the textures at the end of the animation of a slider, there is a little delay at the end of the animation and it has to do with the assignment of the texture. 
Any way to improve this?

https://codepen.io/AlainBarrios/pen/RwWyXWy?editors=0010

**Comment by martinlaxenaire** [comment]
Hi @AlainBarrios,

yes, each time you're setting a new texture source with the `setSource` method, the image will be uploaded to the GPU and will force the browser to decode the image, which could be slow.
It should be faster using `setFromTexture` like that:

```javascript
  changeTexture(currentIndex, nextIndex, duration) {
    const tl = gsap.timeline();

    tl.to(this.plane.uniforms.progress, {
      duration: duration * 1.25,
      value: 1,
      onComplete: () => {
        //this.activeTexture.setSource(this.plane.images[currentIndex]);
        //this.nextTexture.setSource(this.plane.images[nextIndex]);
        
        // avoid a new upload from the CPU to GPU
        // and eventual browser image decoding (slow)
        // by using setFromTexture() instead of setSource()
        // also we'll need to recompute the texture matrices
        this.activeTexture.setFromTexture(this.plane.textures[currentIndex]);
        this.activeTexture.resize();
        this.nextTexture.setFromTexture(this.plane.textures[nextIndex]);
        this.nextTexture.resize();

        this.plane.uniforms.progress.value = 0;
      }
    });

    return tl;
  }
```

Let me know if that works.

Cheers,

**Comment by AlainBarrios** [comment]
Well, it has solved the problem for me. Should I avoid using `setSource`? . Thank you

**Comment by martinlaxenaire** [comment]
Yes, for images I think you can safely use `setFromTexture` over `setSource` it will be faster.

For videos or canvas, you'd still have to upload the textures to the GPU each time your video/canvas has changed so it shouldn't make any big difference after all.

**Comment by ajayns** [comment]
I'm mentioning my question here cause it sounds pretty related. 

Is there any way to bypass the flicker/delay that occurs by freezing the frame at that point? For my case, instead of setting a new source, I initialize a new plane itself (which I think is comparable though) and I'd assumed that `disableDrawing()` function could freeze the frame until I initialize the new plane and then call `enableDrawing()` but that still seems to cause the flicker between old plane removal and new one initialized. 

Any ideas on this @martinlaxenaire ?

**Comment by martinlaxenaire** [comment]
Hey @ajayns, 

I'm not sure to understand your use case scenario, but here are some things you might want to know:
- `disableDrawing()` and `enableDrawing()` are useful if you want to stop rendering your scene (saving CPU) when it's idling. It's not really meant to be used to freeze it.
- Actually some events such as plane's `onReady()` callback or `setSource()` are forcing the scene to re-render even if `disableDrawing()` has been called previously.
- Initializing a new plane has always more impact on performance that setting a texture source (think shaders compilation). Maybe you should try to set it beforehand and switch its `visible ` property, or use the `resetPlane()` method if possible?

Cheers,

**Comment by ajayns** [comment]
Ahh I understand, those two solutions could come in handy. I'll check them out and figure a way, thank you!

**Comment by ajayns** [comment]
Hey again @martinlaxenaire  , I decided to go with the new plane approach as that seemed most suitable for my use case. The issue still seems to persist.

The order of actions would look like: (pseudo-code)
```javascript
plane = addPlane()
plane.visible = false;

plane.onReady(function() {
  plane.visible = true;
  removePlane(prevPlane);
});
```

What I could think of that could be causing the issue would be the momentary blink where the activetexture hasn't been defined as my code is similar to multiple textures example: https://github.com/martinlaxenaire/curtainsjs/blob/3c0dc7ce63039227a68cc6500a192f49323ab5f9/examples/multiple-textures/js/multiple.textures.setup.js
```
           // first we set our very first image as the active texture
            var activeTex = multiTexturesPlane.createTexture({
                sampler: "activeTex",
                fromTexture: multiTexturesPlane.textures[slideshowState.activeTextureIndex]
            });
            // next we set the second image as next texture but this is not mandatory
            // as we will reset the next texture on slide change
            var nextTex = multiTexturesPlane.createTexture({
                sampler: "nextTex",
                fromTexture: multiTexturesPlane.textures[slideshowState.nextTextureIndex]
            });
```
And so would need the activeTexture setup for it to actually render. I'm doing this step before I set the plane visibility to true and I remove the prevPlane but it seems like this seems to be taking longer as it is async - causing the plane to be visible before its textures are handled right. Is there any way of knowing when the createTexture is completed? Or is there any other approach altogether to ensure that the plane is completely loaded and ready before I set it visible?

**Comment by martinlaxenaire** [comment]
Hey @ajayns, 

that's hard to tell without a working codepen or jsfiddle to debug.
It might be caused by the small delay due to texture GPU uploading.
I'm planning on adding texture events in the future (`onSourceLoaded` and `onSourceUploaded`) but you'll have to wait for the next major update.
In the meantime, what about using a timeout:

```javascript
plane = addPlane()
plane.visible = false;

plane.onReady(function() {
  setTimeout(function() {
    plane.visible = true;
    removePlane(prevPlane);
  }, 50);
});
```

Cheers,

**Comment by ajayns** [comment]
Yep, I feel like the super small yet noticeable jag is caused by GPU uploading. And yes for now I'm using a small delay as well but ofc it's hacky so I asked to see if there were any APIs that are usable.

So no problem, this works for now. Also, maybe GPU preloading could prove useful I think in some use cases.

**Comment by martinlaxenaire** [comment]
Yeah I know, there's a lot of room to improve how textures are handled at the moment.
Hopefully the new ES6 version I'm working on will greatly improve that, including texture GPU preloading as well. Here's an insight of how it might look like:

```javascript
var img = new Image();
img.setAttribute("data-sampler", "uTexture");
img.src = "path/to/image.jpg";

const loader = new TextureLoader(curtains);
loader.loadImage(img, (texture) => {
    console.log("img loaded and texture created", texture);
    texture.onSourceUploaded(() => {
        console.log("texture uploaded to GPU", texture);
    });
}, (img, error) => {
    console.log("there has been an error loading the image:", img, error);
});
```

Cheers,

**Comment by ajayns** [comment]
Just letting you know about another thing I noticed. So, when I remove a plane at the end of multiple animations (might be performance thing, I'm unsure), the whole canvas blinks for a frame or so. The temporary fix I found was to set a small timeout after the animations end and then it seems to be working fine most of the time.
