### ISSUE TITLE
Performant approach for using multiple effects on a plane

### ISSUE THREAD

**Issue by ajayns** [martinlaxenaire/curtainsjs#43]
Say I've got a plane that does multiple effects using its fragment shader. The animations including things like a scroll-linked appear, then a mouseover and finally, an exit animation when transitioning out of the page.

What would be the recommended approach to go about this using Curtains that is efficient and performant? The ideas include including all these effects in a single fragment shader but attempting to optimize as to reduce unnecessary calculations when unused. Alternatively, I'm thinking of switching frag shaders for different states: initial appear, in page interaction, exit - this could be by reinitializing or loading new planes.

Edit: Sorry about the whole mixup, I closed the wrong issue by mistake.

**Comment by martinlaxenaire** [comment]
Hey @ajayns, 

if you want to apply multiple effects, just use multiple uniforms to conditionally apply the effects, using `mix()` for example.
As long as you're not abusing if/else statements, for loops or a lot of `texture2D` calls it shouldn't pose any performance issues.

The library does not allow to switch shaders during runtime, and adding new planes does not look like a good idea to me. Both ways would trigger shaders recompilation each time which is quite slow.
So just use on fragment shader and do all your stuff in there.

Cheers,

**Comment by ajayns** [comment]
Hey Martin! 

Hmm, that covers most of my doubts regarding the library, but I guess I'll have to follow best practices and then experiment to optimize performance to ensure shaders run smooth.

Thanks again
