### ISSUE TITLE
Plane size to match image size

### ISSUE THREAD

**Issue by roomfive** [martinlaxenaire/curtainsjs#47]
Really amazing work with curtains.js, thank you!

I've been playing with the [Multiple planes scroll effect with Locomotive scroll](https://www.curtainsjs.com/examples/multiple-planes-scroll-effect-custom-scroll/index.html) demo, and I was wondering if it's possible for the width and height of each plane to be dictated by the image size. So you'd end up with different sized planes as you scroll the page, as opposed to the same width/height each time?

Thanks

**Comment by ajayns** [comment]
Unsure if you mean something else, but the characteristics of each plane is dependent on the size, position of the HTML element. In the particular example you mentioned, checkout the elements with class `plane` - the WebGL planes are of that size and so changing the size of that element should give you different sized planes.

**Comment by martinlaxenaire** [comment]
Hi @roomfive,

as @ajayns said, you just have to change each plane sizes in CSS to get the desired result. Have a look at that codepen for example: https://codepen.io/martinlaxenaire/pen/GRJOxrO

Cheers,

**Comment by roomfive** [comment]
Great, thank you.
