### ISSUE TITLE
Missing some uniform types

### ISSUE THREAD

**Issue by UstymUkhman** [martinlaxenaire/curtainsjs#5]
Hi, I've tried to pass a `mat4` uniform to my shader, but I haven't found a uniform type for it. So I digged down into the source code and I saw it was actually missing along with `mat2` and `mat3` types. I thing it could be useful in some cases, it would be a problem to add this types?

**Comment by martinlaxenaire** [comment]
Hi @UstymUkhman,

you are absolutely right, I totally forgot the mat2, mat3 and mat4 uniforms. I've fixed it now!

Thanks,
