### ISSUE TITLE
WebGL version of image doesn't seem to align

### ISSUE THREAD

**Issue by ZachSaucier** [martinlaxenaire/curtainsjs#52]
I created [a basic, responsive, draggable slider](https://codepen.io/ZachSaucier/pen/b77dc773bab03d3f302d09e116dc5600) using GSAP. I'm now attempting to render it with Curtains so that I can apply some WebGL effects. But when I [attempt to render the images](https://codepen.io/ZachSaucier/pen/3850c1db403e7c9acfad42ee1e440501) they don't seem to match up - the Curtains version has extra padding/white space on the sides. Why is this? And how can I remove the white space? Ignore the color inversion, it's part of the end effect I'll be making.

I'm using [this article](https://medium.com/better-programming/webgl-enhanced-drag-slider-tutorial-with-curtains-js-part-2-bf32aa5a15c0) as a reference of learning about Curtains in case that helps understand where I'm coming from.

**Comment by martinlaxenaire** [comment]
Hi @ZachSaucier, 

The padding/white spaces are caused by this code in your fragment shader:

```glsl
    if(myUV.x < transAmnt || myUV.x > (1.0 - transAmnt)
    || myUV.y < transAmnt || myUV.y > (1.0 - transAmnt)) {
      discard;
    }
``` 

If you remove this part (or just comment the `discard` line, or even change your if condition), it'll work as expected.

I have to confess this one puzzled me for a while and I've spent quite some time focusing on the javascript instead of the glsl. :)

Cheers,

**Comment by ZachSaucier** [comment]
Doh, I should have caught that. Sorry for the trouble. That code is there because in my GLSL-only version that I am mixing with the DOM slider I "cut off" the pixels around the edges so that I can make the image be translated around the bounding rectangle based on the mouse position while not having to repeat any pixels at the edge. 

Since I have you here anyway, do you have any advice on that subject? I could scale up the actual DOM image and do the translation there (before it is passed into WebGL). Would that be easier? Or is there a way with GLSL to scale up the input texture (not past its intrinsic values though) to where I could have some space pixels to use for the translation effect?

**Comment by martinlaxenaire** [comment]
To scale a texture you could use the texture `setScale()` method.
I've checked your pen a bit more and there were a few mistakes (in your uniforms object and the way you're handling the mouse position):

```javascript
function updateMouse(e) {
  if (e.changedTouches && e.changedTouches.length) {
    e.x = e.changedTouches[0].pageX;
    e.y = e.changedTouches[0].pageY;
  }
  if (e.x === undefined) {
    e.x = e.pageX;
    e.y = e.pageY;
  }
  
  mouse[0] = e.x;
  mouse[1] = e.y;
  
  for(let i = 0; i < planes.length; i++) {
    // update the planes mouse position uniforms
    const webglMousePos = planes[i].mouseToPlaneCoords(mouse[0], mouse[1]);
    planes[i].uniforms.mouse.value = [webglMousePos.x, webglMousePos.y];
  }
}


const planes = [];
window.addEventListener("load", e => {
  const curtains = new Curtains({ container: "canvas" });
  const planeElements = document.querySelectorAll(".box");
  
  const params = {
      vertexShaderID: "slider-planes-vs",
      fragmentShaderID: "slider-planes-fs",
      uniforms: {
        radius: { 
          name: "uRadius",
          type: "1f", 
          value: 0.1 
        },
        mouse: { 
          name: "uMouse",
          type: "2f", 
          value: mouse 
        },
        // For the antilaising
        resolution: { 
          name: "uResolution",
          type: "2i", 
          value: [window.innerWidth, window.innerHeight] 
        }
      },
  };
  
  planeElements.forEach((planeEl, i) => {
    // addPlane method adds a plane to our WebGL scene
    // takes 2 params: our HTML referent element and the params set above
    // it returns a Plane class object if creation is successful, false otherwise
    const plane = curtains.addPlane(planeEl, params);

    // if our plane has been successfully created
    if(plane) {
        // push it into our planes array
        planes.push(plane);

        // onReady is called once our plane is ready and all its texture have been created
        plane.onLoading(function(texture) {
          // scale up the texture
          texture.setScale(1.2, 1.2);
        }).onReady(function() {
            // inside our onReady function scope, this represents our plane
            const currentPlane = this;

            // add a "loaded" class to display the title
            currentPlane.htmlElement.closest(".box").classList.add("loaded");
        });
    }
  });
  
});
``` 

Also you'll have to convert your mouse coordinates in your fragment shader:

```glsl
// from vertex coords to text coords
vec2 mouse = (uMouse + 1.0) * 0.5;
```

Is it what you where trying to achieve?

Cheers,

**Comment by ZachSaucier** [comment]
> To scale a texture you could use the texture setScale() method.

Thanks, I figured there would be a method similar to that because I feel like it's a common thing to do.

> there were a few mistakes (in your uniforms object and the way you're handling the mouse position):

Yep, I hadn't gotten around to focusing on that yet. Thanks for doing my work for me! Haha 😉 

> Is it what you where trying to achieve?

Very close! I updated [the pen](https://codepen.io/ZachSaucier/pen/3850c1db403e7c9acfad42ee1e440501?editors=1010) with the changes. The position of the circle doing the fish-eye doesn't match up perfectly with the mouse. I know it has to do with the scaling of the vertex coords to the texture coords. I'm guessing it's getting thrown off because of the setScale() method? I've tried playing around with the conversion a bit but can't seem to get the radius to align. If you could help me understand what's going on there I'd really appreciate it.

**Comment by martinlaxenaire** [comment]
Your mouse position is not correct because you need to apply the texture matrix to it as well.
You could do it in your vertex shader and pass the position as a varying like that:

```glsl
  #ifdef GL_ES
  precision mediump float;
  #endif
  
  // default mandatory attributes
  attribute vec3 aVertexPosition;
  attribute vec2 aTextureCoord;
  
  // mandatory projection and model view matrices are generated by the library
  // it will position and size our plane based on its HTML element CSS values
  uniform mat4 uMVMatrix;
  uniform mat4 uPMatrix;
  
  // this is generated by the library based on the sampler name we provided
  // it will be used to map adjust our texture coords so the texture will fit the plane
  uniform mat4 planeTextureMatrix;
  
  uniform vec2 uMouse;
  
  // texture coord varying that will be passed to our fragment shader
  varying vec2 vTextureCoord;
  varying vec2 vMouse;

  void main() {
      // varying
      // use texture matrix and original texture coords to generate accurate texture coords
      vTextureCoord = (planeTextureMatrix * vec4(aTextureCoord, 0.0, 1.0)).xy;
      // convert from vertex pos to texture pos and apply texture matrix to the mouse position as well 
      vMouse = (planeTextureMatrix * vec4((uMouse + 1.0) * 0.5, 0.0, 1.0)).xy;
    
      // apply our vertex position based on the projection and model view matrices
      gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);
  }
```

Now you can use `vMouse` in your fragment shader and that should work!

Cheers,

**Comment by ZachSaucier** [comment]
Thanks a lot for the help! This part is done now.

I'll have to spend some more time trying to understand how these matrixes and coordinate systems fit together.
