### ISSUE TITLE
GL_REPEAT as default on plane texture instead of GL_CLAMP

### ISSUE THREAD

**Issue by gomako** [martinlaxenaire/curtainsjs#55]
Hi, I'm trying to do some simple image postprocessing and would like the default sampler to be repeated instead of clamped ( [as shown here](https://codepen.io/gomako/pen/vYGPwgb)). 

Is there a way I can do this without creating a texture object and adding it to a plane? I can see in the docs that you can set the wrapS/wrapT as a parameter in the texture object but wondered if there's a way to set it without doing that. I don't really understand how to use `addParent` as the texture doesn't seem to show up. 

Apologies if this is somewhere in an example, I don't seem to be able to find it.

Also, not sure how to add a label to the issue, I'm `seeking-help`

**Comment by martinlaxenaire** [comment]
Hi @gomako, 

there's indeed a way to set the default plane textures wrapping parameters to repeat, by using the texturesOptions object property in your initial parameters.
You'd have to use curtains.js v7+ tho (your pen is actually using the version 6.2).

Remove the curtainsjs script tag in your html and past this in your javascript, it should work:

```javascript
import {Curtains, Plane} from 'https://www.curtainsjs.com/src/index.mjs';

// we are using window onload event here but this is not mandatory
window.onload = function() {


  // pass the id of the div that will wrap the canvas to set up our WebGL context and append the canvas to our wrapper
  var curtain = new Curtains({
    container: "canvas"
  });

  // get our plane element
  var planeElement = document.getElementsByClassName("plane")[0];

  // set our initial parameters (basic uniforms)
  var params = {
    vertexShaderID: "plane-vs", // our vertex shader ID
    fragmentShaderID: "plane-fs", // our framgent shader ID
    texturesOptions: {
      wrapS: curtain.gl.REPEAT, // repeat along X axis
      wrapT: curtain.gl.REPEAT, // repeat along Y axis
    }
  }

  // create our plane mesh
  var plane = new Plane(curtain, planeElement, params);

}
```

**Comment by gomako** [comment]
Thank you! Yes, would help if I could spell the right label.
