### ISSUE TITLE
Curtains.js in React components using React Hooks

### ISSUE THREAD

**Issue by alexolotl** [martinlaxenaire/curtainsjs#56]
Hey there, I'm trying to use Curtains.js in React with React Hooks (and with Gatsby), does anybody have any experience setting this up correctly to avoid any memory leaks or lost references to canvas elements?

I've already looked into this older discussion on the topic (https://github.com/martinlaxenaire/curtainsjs/issues/9), although I notice that it only sets up one curtains instance in the root node (and uses an id in a React component), which seems different from my goal of setting up distinct Curtains instances in different sub components and handling their creation, re-rendering, and destruction separately - and handling dom elements via refs and not id directly in React.

I'm using the useRef() hook to keep reference to my canvas container dom element. Also, I am setting the Curtains and Plane instances in my state with the useState() hook, and calling curtains.dispose() in the deconstructor return of the useEffect() React hook. I'm trying to use textures in my shader via img elements with data-sampler attributes, although I'm not sure if this attribute and how its handled as a uniform in Curtains will play well with React re-renders. 

The problem I'm facing is that it seems to only work sometimes to apply dynamic image src changes to the data-sampler elements - almost as if the uniforms for these textures are not being correctly updated when the React component updates. Either that, or perhaps I am accidentally re-creating or duplicating canvas elements and losing reference to the original 

If anyone has experience with getting this working properly with React hooks, it would be greatly appreciated - thanks!

**Comment by martinlaxenaire** [comment]
Hi @alexolotl,

I don't understand why you'd want to create multiple Curtains instances and I think that it is always a bad idea. You should be able to achieve what you're looking for by creating just one Curtains instance (that you wouldn't ever unmount) and adding/removing only the planes.

Anyway since I think you're not the only one that wonders how to use curtains.js with React hooks, I've created a codesandbox example: https://codesandbox.io/s/sleepy-fire-4697m?file=/src/App.js

There might be other ways to achieve it with React of course.

Cheers,

**Comment by alexolotl** [comment]
Hi Martin, thanks for providing the React hooks sandbox example, helpful to see Curtains.js used with hooks and React context:)

I’ll try to explain what I was hoping to achieve with multiple Curtains instances - perhaps there’s another way I can do so while keeping only one global Curtains canvas container at app root level.  

Using the sandbox example as reference, my goal is to apply different positioning on different variations of the WebGLPlane component. For example, to display one WebGLPlane as position: fixed with negative z index (fixed background), have another plane component with position relative and positive z index to flow with the page content, or perhaps another which is position sticky. (For example, a homepage may use a large fixed background styling, but on a projects page, they may need to be regular flowing elements). 

Here is where I get lost, since I would think that I need separate canvas elements to be able to handle the canvas styling case by case like this (at least for z-index and position). 

What I was previously attempting was to define a Curtains instance, a Plane instance, a canvas wrapper ref, and plane ref all within one component - setting the canvas size and styling to match the plane ref container styling - and then to clean up the Curtains and Plane instances while unmounting the component. Is this an approach I should avoid?

Thanks for the tips, and the library!

**Comment by martinlaxenaire** [comment]
Hi @alexolotl, 

yes, as I can confirm that you should always use only one Curtains instance (and therefore only one webgl context and so on).

Try to play with the `watchScroll` property (setting it to false will simulate a fixed position) and the `moveToFront()` method to handle z indexes. That should cover your needs if I understand well.

Cheers,
