### ISSUE TITLE
Text effects

### ISSUE THREAD

**Issue by ZachSaucier** [martinlaxenaire/curtainsjs#57]
Hey Martin. I know text in WebGL isn't the easiest thing to do but I noticed that sites [like yours](https://www.martin-laxenaire.fr/) do WebGL effects on text while keeping it in sync with the DOM elements. I know that CurtainsJS is meant "to animate images and videos" but do you have any insight as to how to render text as well? Can CurtainsJS help with that process? Any insight you have is welcome including articles about that topic would be appreciated.

**Comment by martinlaxenaire** [comment]
Hey @ZachSaucier, 

at the moment the trick used to display text with curtainsjs is to draw it on a canvas, and use that canvas as a texture.
There are several examples online if you want to have a look at the source code, including one on the documentation website:

https://github.com/martinlaxenaire/curtainsjs/blob/master/examples/multiple-planes-canvas-text/js/multiple.planes.canvas.setup.js
https://codepen.io/martinlaxenaire/pen/OJVKVYa
https://codepen.io/AlainBarrios/pen/jOOKWNX

Hope that helps!

Cheers,

**Comment by ZachSaucier** [comment]
Thanks a lot for the links!
