### ISSUE TITLE
Print the program log on link errors?

### ISSUE THREAD

**Issue by greggman** [martinlaxenaire/curtainsjs#58]
As it is if there is a link error when linking a shader program the code detects the error but it doesn't print / include the program info log as in (`gl.getProgramInfoLog(program)`). This means if a user gets a link error, like they mis-named a varying in their fragment shader so it doesn't match they get no message that might help them find the error.

In other words this line https://github.com/martinlaxenaire/curtainsjs/blob/master/src/core/Program.js#L165

```
  throwWarning(this.type + ": Unable to initialize the shader program.");
```

could maybe be this?

```
  throwWarning(this.type + ": Unable to initialize the shader program. " + this.gl.getProgramInfoLog(this.program));
```

**Comment by martinlaxenaire** [comment]
Hey @greggman,

that's a good idea indeed. I'll be adding it in the next release.
Thanks for the suggestion! Pretty glad to see you here by the way since curtainsjs wouldn't exist without your webglfundamentals tutorials and all your SO posts.

Cheers,
