### ISSUE TITLE
multiple Plane Using Locmotive Scroll

### ISSUE THREAD

**Issue by Dushyant1295** [martinlaxenaire/curtainsjs#59]

**Comment by martinlaxenaire** [comment]
Hi @Dushyant1295, 

I'd say this is most probably a CSS or javascript locomotive scroll setup issue, but without the full code it is hard to say.
Could you post a jsfiddle or codepen demonstrating the issue?

Cheers,

**Comment by Dushyant1295** [comment]
Hi  Sorry  !  Give me few min i'll demonstrate you in codepen

**Comment by Dushyant1295** [comment]
https://codepen.io/dushyant1295/pen/ExygrEK
