### ISSUE TITLE
Curtains is not defined

### ISSUE THREAD

**Issue by jesperlandberg** [martinlaxenaire/curtainsjs#6]
Hi, I'm getting the error "Curtains is not defined", just trying to implement the basic example.

My code:

```
import 'curtainsjs/build/curtains'

function backgroundScene() {
	const curtain = new Curtains('intro-canvas')
	const planeEl = document.querySelector('.js-intro__plane')

	const params = {
        vertexShaderID: "plane-vs", // our vertex shader ID
        fragmentShaderID: "plane-fs", // our framgent shader ID
        uniforms: {
            time: {
                name: "uTime", // uniform name that will be passed to our shaders
                type: "1f", // this means our uniform is a float
                value: 0,
            },
        }			
	}

	const plane = curtain.addPlane(planeEl, params)

	plane.onRender(function() {
		plane.uniforms.time.value++
	})
}

backgroundScene()
```

Also if i try `import Curtains from 'curtainsjs'` I get an error saying `can't find module curtainsjs`

Am I doing something wrong?

**Comment by martinlaxenaire** [comment]
Hi @jesperlandberg,

there was indeed an issue with the npm version of the lib.
This should be fixed now. Uninstall your previous package and then run:

`npm install curtainsjs`

Then in your project you'll just have to import it like that:

`import {Curtains} from 'curtainsjs';`

Thanks,
