### ISSUE TITLE
Cannot create WebGL context in ANY browser on windows >= 8.1

### ISSUE THREAD

**Issue by miked-known** [martinlaxenaire/curtainsjs#60]
I'm getting errors in windows browsers while attempting to use curtainsjs in a project. As a verifiable example if you pull up the curtains site, I'm getting the same error with all of the examples. I have tried various virtual machine versions of windows browsers as well as testing on browserstack.

Any ideas?

![image](https://user-images.githubusercontent.com/70295385/96645087-eb9e6c80-12de-11eb-96be-90d77fa8eae2.png)
![image](https://user-images.githubusercontent.com/70295385/96645138-01139680-12df-11eb-9763-489a2d1a0f40.png)

**Comment by miked-known** [comment]
If it helps I isolated just the logic you use to get the context and ran that it isolation in a codepen and that is working fine. So it doesn't seem like that is the issue.

**Comment by miked-known** [comment]
After doing some additional digging on this, it appears the issue may be related to lack of full WebGL support on VMs while still technically supporting WebGL via feature detection.

**Comment by martinlaxenaire** [comment]
Hi @miked-known,

I was indeed thinking it might have to do with the VM itself (especially since I'm on Windows 10 myself) but thanks for digging into this.
I'd also have suggested you could try setting the `failIfMajorPerformanceCaveat` to `false` just in case.

Cheers,

**Comment by miked-known** [comment]
Good to know, I'll definitely check that parameter and see if it helps. After doing some further checking it seems that the pre 7 version of the library DOES work on VMs so something appears to have changed in the new version. My gut is it might be something to do with the es6/module/babel stuff although I haven't had a chance to 100% confirm this. Thanks again, for a great library!

**Comment by miked-known** [comment]
Sorry to keep coming back on this. Just want to pass along as much useful information as I can. After some further testing curtains version 6.2.2 works fine in a Win10 VM, where the identical shaders and logic in 7.1.1 throws the `CLAMP_TO_EDGE` error

**Comment by martinlaxenaire** [comment]
Hey @miked-known,

many thanks for all those tests. I'm still thinking this could be related to the `failIfMajorPerformanceCaveat` parameter:

- Versions < 7.0 had no way to set the `failIfMajorPerformanceCaveat` WebGL context attribute, and the context was therefore created with this property set to `false` by default.
- Versions >= 7.0 introduced this option and it is now set to `true` by default on context creation.

I'd really appreciate if you could run one more test with a version >= 7.0 and this option set to `false` on init. That would be really helpful!

Cheers,

**Comment by miked-known** [comment]
Sure thing, will try that option out and report back. Thanks again

**Comment by droplab** [comment]
Hi Martin, apologies on the slow turnaround on this. Please keep it open and I will report back with results as soon as I can test - should be soon. Thanks

**Comment by dejardine** [comment]
Getting this exact issue too. Did we ever confirm this was related to Browserstacks setup or is it actually a bug?

**Comment by dejardine** [comment]
*Update* I went to the local PC retailer and tried to replicate my version of the bug on a dozen windows laptops and couldn't. I'm thinking Browserstack have limited WebGL support, which is concerning as I pay them money each month for their service!

**Comment by dejardine** [comment]
Wow, I submitted a ticket to BrowserStack report and they replied:

"I would want to share that currently, WebGL is only supported on OS X machines in 'Live'.
​
Adding WebGL support on our Windows machines is on our long term product roadmap, I will be unable to share an ETA at the moment. I have noted down your request and you will be notified should there be any development towards this."

​

**Comment by martinlaxenaire** [comment]
Hi @dejardine, 

thanks for the feedback, that's what I was thinking.
I'll leave this open waiting for some @droplab news on that topic and then maybe we'd be able to close that issue.

Cheers,

**Comment by martinlaxenaire** [comment]
Closing this one as it seems to be related to browserstack and WebGL and not the library itself.
