### ISSUE TITLE
Multiple Planes with Locmotive Scroll

### ISSUE THREAD

**Issue by Dushyant1295** [martinlaxenaire/curtainsjs#61]
Hi Sir Thank you for this great library 🤍
I have an issue with locomotive scroll

1. Images(planes) are not showing in full Height ( even not Scroll only 2 planes( image ) are visible );
2. And also notice some lag and jerks with locomotive How To Optimize Performance I want to use Multiple Planes !

⇾ I'm using it on multiple pages using barba js and invoking it in init() function
Here is a code pen Links for Better Understanding ⇾

https://codepen.io/dushyant1295/pen/ExygrEK

Without Locomotive it just works fine ⇾
https://codepen.io/dushyant1295/pen/jOrMJrP

Thanks !

**Comment by martinlaxenaire** [comment]
Hi @Dushyant1295,

there were a couple issues with you pen:
- You were translating the webgl canvas as well, that was why it looked like it was cropped when you scrolled down.
- You were not updating the planes positions inside the locomotive scroll `scroll` event.

Here's a working pen: https://codepen.io/martinlaxenaire/pen/NWrRJzx

Cheers,

**Comment by Dushyant1295** [comment]
@martinlaxenaire Thank you So much  💛
