### ISSUE TITLE
Ping-pong-shading-flowmap example failing in Safari (desktop & mobile)

### ISSUE THREAD

**Issue by andrewleek-droplab** [martinlaxenaire/curtainsjs#62]
While working on a something similar to your flowmap example (utilizing the new PingPongPlane class) i found that Safari was throwing some errors and was unable to render my plane.  I then went to load up your ping-pong-shading-flowmap example directly and got the same error and a blank page.  The screen cap is from desktop.  On mobile i have only visually confirmed that Im getting a blank screen (i have not checked the console on mobile).

I was using Curtains v7.1.2

Thanks for all the hard work on a great library!

![Screen Shot 2020-10-22 at 2 06 14 AM](https://user-images.githubusercontent.com/64859328/96803015-6fee0e00-140b-11eb-93a2-1cf8153385f9.png)

**Comment by martinlaxenaire** [comment]
Hi @andrewleek-droplab,

Thanks for reporting that issue!
It should be fixed in v7.1.3 - 3acc7c6914683ec1c7a9264cec26a73a9d0c1eae

Cheers,
