### ISSUE TITLE
ShaderPass not working with ping-pong-shading-flowmap example

### ISSUE THREAD

**Issue by andrewleek-droplab** [martinlaxenaire/curtainsjs#64]
Ive been working off your ping-pong-shading-flowmap example but have been trying to apply the effect to a shader pass instead of to a plane.

I have created a fiddle based off of your example illustrating the problem.

You can find it here:
https://jsfiddle.net/AndrewLeek/cskez54y/16/

1. I am creating a plane based on the 'flowmap' div with a basic vert/frag shader instead of the displacement vert/frag shader.
2. I have altered the displacement vert/frag shader to be inline with the format outlined in: https://www.curtainsjs.com/shader-pass-class.html
3. I am creating a shader pass and assigning it the displacement vert/frag shader.

The result i am getting is a black and white (inverted) version of the image and am unable to see any flowMap data being drawn.

Could anyone take a look and let me know what i am doing wrong here...

Thanks in advance.

**Comment by martinlaxenaire** [comment]
Hey @andrewleek-droplab,

combining ping pong planes and shader passes is a bit tricky. However it is possible and actually you were close to getting it.

The idea is to create a `RenderTarget`, assign it to the planes you want to be affected by the effect, and then create the `ShaderPass` with the render target as parameter.
Here is a working fiddle: https://jsfiddle.net/z58a2h3r/

Cheers,

**Comment by andrewleek-droplab** [comment]
Thanks @martinlaxenaire, that does indeed work!

Although admittedly I am a bit confused as I thought a shader pass created its own RenderTarget internally which defaults to the curtains instance when none is set explicitly (which would be the default to which the planes are rendered to as well).  

As you said its a bit tricky, so Im sure Im missing something about how things are working internally.

This is more a curiosity, so regardless, thanks for the help, as this fixed the issue i was seeing in the fiddle...

Locally, however it didnt quite fix things, as there turned out to be a compound issue.... but I have solved this and was wondering if you could weigh in on it as well:

I have modified the fiddles a bit to better fit my local use-case and have two fiddles to illustrate the issue:

This first one is working as expected with your help...
https://jsfiddle.net/AndrewLeek/hm84se2j/21/

This second one illustrates the secondary issue i was having locally...
https://jsfiddle.net/AndrewLeek/hm84se2j/22/

The only difference is that in the second fiddle, I am creating the ping-pong-plane after creating the four image planes.  For some reason this breaks everything and i get no flowmap input/interaction.

Any light you can shed on this would be greatly appreciated as I was pulling my hair out trying to figure out why it was not working...

Once again, thanks for a great product and the timely responses.
Cheers,
