### ISSUE TITLE
"SecurityError: The operation is insecure"

### ISSUE THREAD

**Issue by alexolotl** [martinlaxenaire/curtainsjs#68]
Hey there. I'm getting "SecurityError: The operation is insecure" when trying to view my dev site on Safari. It works fine with Chrome though.

The traceback is:

```
SecurityError: The operation is insecure.
▼ 10 stack frames were expanded.
_upload
node_modules/curtainsjs/src/core/Texture.js:835
setSource
node_modules/curtainsjs/src/core/Texture.js:547
_onSourceLoaded
node_modules/curtainsjs/src/core/Texture.js:1015
_sourceLoaded
node_modules/curtainsjs/src/loaders/TextureLoader.js:102
loadImage
node_modules/curtainsjs/src/loaders/TextureLoader.js:328
loadImage
node_modules/curtainsjs/src/core/Mesh.js:352
loadImages
node_modules/curtainsjs/src/core/Mesh.js:414
_initSources
node_modules/curtainsjs/src/core/Plane.js:980
_initPlane
node_modules/curtainsjs/src/core/Plane.js:170
Plane
node_modules/curtainsjs/src/core/Plane.js:119
```

Initiating from when I call new Plane(state.curtains, planeRef.current, planeParams) within a component of my React / Gatsby app (using images sourced from the headless CMS Prismic). Since it works fine on Chrome, I'm guessing this must be some crossOrigin or CORS error, although it seems passing crossOrigin: "anonymous" to the planeParams does't help.

Any ideas?

Thanks

**Comment by martinlaxenaire** [comment]
Hi @alexolotl,

this definitely looks like a CORS issue. It's most probably coming from a Safari setting, your framework setup and/or the way you retrieve you data from Prismic. You should also have a look at the response headers.

Cheers,

**Comment by martinlaxenaire** [comment]
I'm closing this issue as CORS issues are independant from curtainsjs.
Feel free to re-open it if you suspect this is due to something else.
