### ISSUE TITLE
Possible to use canvas as texture?

### ISSUE THREAD

**Issue by iamryanyu** [martinlaxenaire/curtainsjs#7]
First of all, thanks so much for this great library!

At the moment, this library allows us to use an image or video as a texture, but I am wondering if there is any way I can use a canvas as a texture?

Many thanks in advance!

**Comment by martinlaxenaire** [comment]
Hi @iamryanyu,

unfortunately, it isn't possible to use canvas as textures yet, however it is on top on my todo list.
I'll let you know when I'll have time to work on it.

Thanks,

**Comment by iamryanyu** [comment]
Awesome, looking forward to it! 👍

**Comment by martinlaxenaire** [comment]
Hi @iamryanyu,

I've just pushed an update that lets you use canvas as texture, either by inserting a <canvas> tag inside your plane HTML element or by using a loadCanvases() method.

Here is a working example: https://www.martin-laxenaire.fr/libs/curtainsjs/examples/simple-canvas-plane/index.html

Thanks,

**Comment by iamryanyu** [comment]
Wow that's great, thanks for your hard work!
