### ISSUE TITLE
Flowmap resize issue

### ISSUE THREAD

**Issue by andrewleek-droplab** [martinlaxenaire/curtainsjs#71]
Hey Martin,

Im seeing some strange distortion with a flowmap setup.

Its modeled off the flowmap part of your new example: https://www.curtainsjs.com/examples/gsap-click-to-fullscreen-gallery/
because it seemed to be working fine on resize, but after integrating things locally, i am seeing some strange distortion on resize.

Basically on initial load everything is working fine, but if you resize either smaller or larger things get messed up.  I have attached some images to illustrate what im seeing.

![Start Large](https://user-images.githubusercontent.com/64859328/99132763-c7048e80-2617-11eb-84a2-911f40205eaa.png)
![Resized Small](https://user-images.githubusercontent.com/64859328/99132786-df74a900-2617-11eb-8cdb-e74ca78bc0ab.png)
![Start Small](https://user-images.githubusercontent.com/64859328/99132793-e7344d80-2617-11eb-90b8-9668e6eadbba.png)
![Resized Large](https://user-images.githubusercontent.com/64859328/99132807-f1564c00-2617-11eb-8869-ee46fab92459.png)

Let me know if you need any more info.

Regards,
Andrew

**Comment by martinlaxenaire** [comment]
Hi @andrewleek-droplab,

I've tried to reproduce this bug on my side (on Windows, both on FF and Chrome) but without any luck.
Could you tell me more about your OS and browser versions? Is this happening with any browser?
I guess you're also having the bug on this example as well: https://www.curtainsjs.com/examples/ping-pong-shading-flowmap/index.html ?

Cheers,

**Comment by andrewleek-droplab** [comment]
@martinlaxenaire 

I figured out what was wrong ... it turned out to be some old code that causing the issue.
To be specific I had flowMap.updatePosition(); within the flowMap.onRender function.  While it is unnecessary and makes no sense in the context of a ping-pong-plane (once again it was some old code from standard planes) it didnt cause any issue before the 7.3 update.  

I have added it to a fiddle so you can see the result (line 291):
https://jsfiddle.net/AndrewLeek/fgLjo1y3/7/

Im not sure if its a bug since like i said calling updatePosition doesnt really make all that much sense... but it definitely is causing an unexpected issue.

Thanks for you attention on this, and sorry for raising an issue if this is not a bug.

Regards,
Andrew

**Comment by martinlaxenaire** [comment]
Hey @andrewleek-droplab, 

This one is fixed in v8.0.0

https://jsfiddle.net/605ohj9e/

Cheers,
