### ISSUE TITLE
Simple Video Plane - change size of video / zoom in

### ISSUE THREAD

**Issue by joehuggans** [martinlaxenaire/curtainsjs#72]
Hi,

First thank you for this great library and the React project, it is absolutely brilliant.

And excuse me if this is beyond the scope of the issue queue, in which case please feel free to suggest how I could get further help with this problem if it is available, happy to pay for time.

I am trying to create something like this effect - https://codesandbox.io/s/react-curtains-simple-video-plane-ckozr

However I want the video to be zoomed in, right now we can see all of the video pretty much, I would like only the central 50% of the video to be visible.

I have tried setScale but this scales the entire plane (obviously!) I just want to scale the video.

Maybe this is not possible?

Thanks :)

**Comment by martinlaxenaire** [comment]
Hey @joehuggans,

this is definitely possible, you should just use the texture `setScale()` method ([see documentation](https://www.curtainsjs.com/texture-class.html#set-scale)).
If you are using [react-curtains](https://github.com/martinlaxenaire/react-curtains), just add an `onLoading` prop to your `Plane` component with that callback:

```javascript
const onLoading = (plane, texture) => {
  texture.setScale(new Vec2(2, 2));
};
``` 

That should work.

Cheers,

**Comment by joehuggans** [comment]
Thanks very much, I used this example - https://github.com/martinlaxenaire/curtainsjs/blob/master/examples/gsap-click-to-fullscreen-gallery/js/click.to.fullscreen.gallery.setup.js

And in my onReady method did

`const onReady = (plane) => {
    plane.textures[0].setScale(new Vec2(2, 2));
  };`

Thanks again.
