### ISSUE TITLE
Curtains with different image sources based on the viewport size

### ISSUE THREAD

**Issue by ZachSaucier** [martinlaxenaire/curtainsjs#73]
Hey Martin,

Do you have any examples of CurtainsJS working with different image sources depending on the viewport size? It could or could not use the `<picture>` element. I haven't seen any material or demos on the subject. Looking at the texture docs I don't see a straightforward way of doing this sort of thing but I very well could be missing something. Perhaps this sort of thing is what a [texture loader](https://www.curtainsjs.com/texture-loader-class.html) could be used for? Any direction would be appreciated.

**Comment by martinlaxenaire** [comment]
Hey @ZachSaucier, 

There is no built-in way to handle dynamic srcsets but it is fairly easy to mimic it.
The idea would be to load all images beforehand, create a texture and then use its `setSource()` method based on your condition:

```javascript
// curtains is a Curtains instance and plane is a Plane
const texture = plane.createTexture({
    sampler: "uResponsiveTexture"
});

const setResponsiveTexture = () => {
    // get window sizes without triggering reflow
    const curtainsBBox = curtains.getBoundingRect();

    // landscapeImage and portraitImage are 2 previously loaded image elements
    if(curtainsBBox.width >= curtainsBBox.height) {
        texture.setSource(landscapeImage);
    }
    else {
        texture.setSource(portraitImage);
    }
};

setResponsiveTexture();

plane.onAfterResize(() => {
    setResponsiveTexture();
});
```

If you're thinking about saving bandwidth tho, then you'll be disappointed because as you can see you'll need to load all images sources anyway if you want to send them to the GPU.
Is this what you were looking for?

Cheers,

**Comment by ZachSaucier** [comment]
Saving on bandwidth is the goal. Shame that textures can't be loaded after things are set up.

Is there a way to only load a texture dependent on the viewport at least? Meaning that we just load one texture depending on the starting viewport size. If a user resizes to a larger screen nothing happens. That way we could save on bandwidth and it'd look fine except for the rare situation when they resize to make the page larger.

Another approach would be to create new planes when new image sources are needed. Would that work?

**Comment by martinlaxenaire** [comment]
My first answer may not have been clear, sorry about that.
The thing is, you cannot upload a texture to the GPU if the image source itself is not already loaded (this is not a curtainsjs limitation, it's just how WebGL works).
That being said, this is up to you to load the right image and use it as your texture source whenever you want.

I've made this quick codepen to demonstrate how to achieve what I think you are trying to do: https://codepen.io/martinlaxenaire/pen/abmvyNG

Was this helpful?

Cheers,

**Comment by ZachSaucier** [comment]
Yes, thanks a lot for that approach, Martin!

**Comment by ZachSaucier** [comment]
.setSource() is what I was missing. I was looking in the plane docs for something like that - didn't think that the texture itself could switch out its source 🙂  Thanks a lot for the clear demo!

**Comment by ZachSaucier** [comment]
In my actual project I used data attributes to specify the image sources at different sizes and used a loop to keep the code more DRY:

```
const planeTexture = plane.createTexture({
  sampler: "planeTexture"
});

const images = {
  small: {
    src: planeEl.dataset.smallimg,
    img: null,
    minWinWidth: 992
  },
  medium: {
    src: planeEl.dataset.mediumimg,
    img: null,
    minWinWidth: 768
  },
  large: {
    src: planeEl.dataset.largeimg,
    img: null,
    minWinWidth: -1
  },
};

// set the texture source dynamically based on viewport size
const setResponsiveTexture = () => {
  // be careful it takes curtains pixelRatio into account
  const curtainsBBox = curtains.getBoundingRect();

  for(const size in images) {
    const imgInfo = images[size];

    if(curtainsBBox.width >= imgInfo.minWinWidth && plane.userData.planeTexture !== size) {
      plane.userData.planeTexture = size;
      
      if(imgInfo.img) {
        planeTexture.setSource(imgInfo.img);
      }
      else {
        const image = new Image();
        image.addEventListener('load', () => {
          imgInfo.img = image;
          planeTexture.setSource(imgInfo.img);
        });
        image.crossOrigin = "anonymous";
        image.src = imgInfo.src;
      }

      break;
    }
  }
};

setResponsiveTexture();

plane.onAfterResize(() => {
  setResponsiveTexture();
});
```

Thanks again for the help!
