### ISSUE TITLE
LH Performance Issue

### ISSUE THREAD

**Issue by ceiphr** [martinlaxenaire/curtainsjs#76]
Here is my site running a WebP image animated with https://github.com/martinlaxenaire/react-curtains:
https://dev.ceiphr.com/
[LH Report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdev.ceiphr.com%2F)

Here is my site running a WebM video (~600kb):
https://www.ceiphr.com/
[LH Report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.ceiphr.com%2F)

The TTI and TBT are colossal when curtains is running. Is this normal behavior?

**Comment by martinlaxenaire** [comment]
Hey @ceiphr,

I think you were using https://web.dev/measure/ to generate your report. It looks like this online tool is not really suitable to test WebGL websites. Here's what I've got by running a LH report on your site on Chrome on my side:

![Sans titre-1](https://user-images.githubusercontent.com/38728843/103620777-6406e800-4f34-11eb-8297-42b6e1938c52.jpg)

If you want to run tests with online tools I suggest you to use https://www.webpagetest.org/ instead: https://www.webpagetest.org/result/210105_Di16_1096474056b90d1db4db63709dbe5987/

Cheers,

**Comment by ceiphr** [comment]
That makes sense. I forgot this was WebGL. Thank you!
