### ISSUE TITLE
AVIF format support?

### ISSUE THREAD

**Issue by kekkorider** [martinlaxenaire/curtainsjs#78]
**Is your feature request related to a problem? Please describe.**
I'm working on a project with AVIF images and it seems like CurtainsJS cannot handle them.  This is the error message I get

```
this source could not be converted into a texture: /images/homepage/_avif/home-01.avif
```

**Describe the solution you'd like**
CurtainsJS to handle AVIF images 😁

**Describe alternatives you've considered**
For now I'm using WebP images as a fallback.

**Additional context**
Nothing else to report.

**Comment by martinlaxenaire** [comment]
Hey @kekkorider! 

I've updated the `TextureLoader` accepted file extensions in v8.1.0, that should solve your issue (even tho AVIF browser support seems kinda bad at the moment). See 88bc2f8ef22d3b28f24a8a898de15d64b2d013a8

Cheers!

**Comment by kekkorider** [comment]
> even tho AVIF browser support seems kinda bad at the moment

You're right!
It's just that the project I'm working on has more than 50 images to load and it takes time even if I use WebP images, so AVIF support was a big _nice to have_.

Thanks a lot btw, I will try v8.1.0 and let you know ✌️

**Comment by kekkorider** [comment]
My reaction when I saw it working 👇

![giphy](https://user-images.githubusercontent.com/5191941/111839423-0e1ecb00-88fb-11eb-9700-f56138a8edc2.gif)
