### ISSUE TITLE
Can't use image and video textures together? (v8.0.5)

### ISSUE THREAD

**Issue by tiffk935** [martinlaxenaire/curtainsjs#79]
When using only video textures or only image textures with a displacement shader works fine, 
but it doesn't work as expected if using video and image together.

Here is [codepen](https://codepen.io/tiffk935/pen/ExNMWeb).

**Comment by martinlaxenaire** [comment]
Hi @tiffk935, 

there were indeed some issues with the `setSource` method. It should be fixed now in v8.1.0 (see [codepen](https://codepen.io/martinlaxenaire/pen/ZEBNyMV)).

Cheers,

**Comment by tiffk935** [comment]
Thanks!!
