### ISSUE TITLE
Use with more than 2 textures

### ISSUE THREAD

**Issue by AlbanCrepel** [martinlaxenaire/curtainsjs#8]
Hi !
First of all, thank you for this library and keep up the good work !

I am new to Webgl, and I followed this example : [https://www.martin-laxenaire.fr/libs/curtainsjs/examples/multiple-textures/index.html](https://www.martin-laxenaire.fr/libs/curtainsjs/examples/multiple-textures/index.html)

I can't get it to work with more than 2 textures...

Let's suppose I have 4 images. And I want the effect to be the same when going from the first texture to the second, and from the second to the third for example. And backwards from the third texture to the second texture, and from the second texture to the first.

Is there any way to have a generic code that would render the correct effect based on the texture we are currently showing and the one we are going to display ?

**Comment by martinlaxenaire** [comment]
Hi @AlbanCrepel,

this has been already discussed here: #3  
You might also want to check that codepen: https://codepen.io/martinlaxenaire/pen/KeQpLO

Thanks,

**Comment by AlbanCrepel** [comment]
Thank you very much @martinlaxenaire ! I am sorry I didn't see this past issue before...
