### ISSUE TITLE
updateScrollValues() not working when resizing the window

### ISSUE THREAD

**Issue by tiffk935** [martinlaxenaire/curtainsjs#81]
Hi,

Using `curtains.updateScrollValues()` in `onReady()` works perfect, but it seems not working when resizing the window ([See Codepen](https://codepen.io/tiffk935/pen/LYxRWgZ)).

``` js
window.onresize = () => {
  curtains.updateScrollValues(0, window.pageYOffset-document.getElementsByTagName('canvas')[0].offsetTop);
}
```

Is there any way to solve this problem?
Thanks!

**Comment by martinlaxenaire** [comment]
Hey @tiffk935,

if your canvas container isn't fixed, then there's no need to update its scroll values using `updateScrollValues()`.
You can safely remove those lines.

In your case it's just the `<div class="multi-textures">` that is not correctly positioned in CSS. You should just add a `position: relative` to your `#page-wrap` element and that should fix it.

Cheers,

**Comment by tiffk935** [comment]
@martinlaxenaire Thank you so much!!
