### ISSUE TITLE
Video Plane - no texture bound to the unit 0

### ISSUE THREAD

**Issue by maximilianberndt** [martinlaxenaire/curtainsjs#82]
When trying to create a basic video scene like from the [getting started page](https://www.curtainsjs.com/get-started.html#videos-textures), I keep getting this warning: `RENDER WARNING: there is no texture bound to the unit 0`

[See Codepen](https://codepen.io/maximilianberndt/pen/XWpaBGW)

Am I just not seeing something obvious or is there any way to fix this?
Thanks!

**Comment by martinlaxenaire** [comment]
Hey @maximilianberndt,

Oooops, I had made a ridiculous mistake with the videos and canvases autoloading in v8.1.1 - see d76ec0a8a9c8c94dec2c5a94a3737d285df1781c :sweat:

This should be fixed in v8.1.2, sorry about that. Hope it's working now.

Cheers,

**Comment by maximilianberndt** [comment]
Damn that was quick @martinlaxenaire.

Thanks a lot, works like a charm 🙏
