### ISSUE TITLE
Changing current shaders

### ISSUE THREAD

**Issue by JoyMonteiro** [martinlaxenaire/curtainsjs#85]
Hello,

Thanks for the great project, it has significantly lowered the bar for people like me who want to
do simple things with webgl!

I wanted to know if there is any way to change the shaders being used by curtainsjs (let's say
if the user chooses some effect and the website has to respond).

TIA,
Joy

**Comment by martinlaxenaire** [comment]
Hi @JoyMonteiro, 

There's no way to change shaders during runtime, for many reasons, including performance (program would have to be compiled again - which is slow and CPU intensive).

You could handle everything in one shader and switch the desired effect based on an uniform, or even create two planes with different shaders using the same HTML element, and toggle their visibility based on some user interaction.

Hope that helps.

Cheers,

**Comment by JoyMonteiro** [comment]
Thanks for the clarification, Martin. Switching seems to be the better option, since having two planes might mean that the GPU is doing twice the computation.
