### ISSUE TITLE
Different shaders for different events

### ISSUE THREAD

**Issue by yanalexandrov1987** [martinlaxenaire/curtainsjs#88]
Hello. How can I use different shaders for the same canvas, but on different events: mouse movement and click on ?

**Comment by ZachSaucier** [comment]
You use uniforms to pass info to shaders. So apply multiple shaders to the same canvas with different uniforms to them - one for the mouse info, one for the click info.

**Comment by martinlaxenaire** [comment]
Hi @yanalexandrov1987,

@ZachSaucier is absolutely right, you should use different uniforms to handle different events, and use them all in one shader.

See also #85 

Cheers,
