### ISSUE TITLE
Creating a GSAP and CurtainJs Slider Canvas Image Issue

### ISSUE THREAD

**Issue by saadtanvir1994** [martinlaxenaire/curtainsjs#89]
Creating a GSAP and CurtainJs Slider with onScroll but the last plane(slide) image is always shown when the canvas is rendered!

**Comment by ZachSaucier** [comment]
Please make a minimal and complete demo of the issue if you'd like help debugging.

**Comment by saadtanvir1994** [comment]
I am creating a slider with GSAP and curtains (applying wave effect on image). I want to change the content of the slider along with image but I am not able to achieve that.  Text is changing but `opacity` or `display: none` for plane is not working like current slide plane is fade out and next slide plane is fade in.

Codepen Link: https://codepen.io/saadtanvir/pen/gOWMPMr

**Comment by ZachSaucier** [comment]
It looks like you're attempting to fade the _image element_ in and out. That doesn't make much sense because you want the image to be rendered by Curtains (on a canvas). You should instead have curtains fade out the old texture and fade in the new one.

Also you're making some of [the most common GSAP mistakes](https://greensock.com/mistakes/).

**Comment by saadtanvir1994** [comment]
Thank you for your response! Please let me know how I can do it: "You should instead have curtains fade out the old texture and fade in the new one."

**Comment by martinlaxenaire** [comment]
Hey @saadtanvir1994,

As @ZachSaucier pointed out, you need to create as much planes as elements in your slider, and tween a `uniform` like `uOpacity` to handle each plane's opacity.
There are plenty examples on the lib documentation's website and CodePen available to point you in the right direction.

I'm closing this as this clearly isn't related to a bug.

Cheers,
