### ISSUE TITLE
WebGL2 Support

### ISSUE THREAD

**Issue by GeorgeHastings** [martinlaxenaire/curtainsjs#97]
I converted my vertex and fragment shaders to WebGL2 but got an error that shader versions didn't match.

I found that the library creates default shaders starting at line 2879 in v8.1.2  and tried to adapt it. Everything seems to work except the critical #version 300 es prefix. I tried about a dozen different things and kept getting an empty string syntax error. 

Any suggestions OR other gotchas about this upgrade?

**Comment by martinlaxenaire** [comment]
Hi @GeorgeHastings,

this is hard to say what could be wrong with your shaders without an example, but I assume this might come from a syntax error somewhere.

Here is a dummy working example of GLSL 3.0 shaders with curtains.js: https://codepen.io/martinlaxenaire/pen/QWqGBbR

Cheers,

**Comment by GeorgeHastings** [comment]
Thanks @martinlaxenaire, I'm using ShaderPasses without declaring the vertexShader which was defaulting to the gl1 base shader. I still haven't got it working but there's a lot going on in my code so I will close this issue as the GLSL3.0 seems to be resolved.
