### ISSUE TITLE
Typescript types.

### ISSUE THREAD

**Issue by profispojka** [martinlaxenaire/curtainsjs#98]
**Is your feature request related to a problem? Please describe.**
There are no types in curtainjs.

**Describe the solution you'd like**
Enhance curtainjs with Typescript types.

**Describe alternatives you've considered**
I can make the types myself, but it would be better to change them in the library, as the autor is more profound in knowing how the library works.

**Additional context**
-

**Comment by martinlaxenaire** [comment]
Hi @profispojka,

I'm sorry but adding Typescript support isn't somehting I'll be working on.

Cheers,

**Comment by Blakeinstein** [comment]
Added a typescript definition file based on the docs
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66027
